name: jupyterlab-starters-docs

channels:
  - conda-forge
  - defaults

dependencies:
  - cookiecutter
  - importlib_metadata
  - jupyterlab >=1.2.4,<1.3
  - nbsphinx
  - nodejs >=11,<12
  - python >=3.7,<3.8.0a0
  - python-fastjsonschema
  - python-graphviz
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - ujson
